version: "3.8"

services:
    db:
        image: postgres:13
        container_name: itadb-dev-data
        volumes:
            - itadb-dev-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_USER: ${DB_USER}
        networks:
            - backend

    redis:
        image: redis:6
        container_name: redis-dev-data
        command: redis-server --requirepass $REDIS_PASSWORD --appendonly yes
        networks:
            - backend

    ita-api:
        build:
            context: .
            dockerfile: Dockerfile.dev
        image: ita-api:dev
        container_name: ita-api-dev
        platform: linux/x86_64
        volumes: 
            - /home/node/app/node_modules
            - .:/home/node/app
        ports:
            - ${PORT}:${PORT}
        networks:
            - backend
        depends_on:
            - db
            - redis

volumes:
    itadb-dev-data:
        name: itadb-dev-data

networks:
    backend:
        name: itabe-network-backend
        driver: bridge